# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05fd56bc1d627348b6a03228eead26bf1f7ab5eb822bb076990f9abec3a41156a133762b7f2320896301a0542f3626280e643d25fa7e6155fc7c99a7e0ceefa3

test:
  secret_key_base: 8987b9c07458a86f5f5aaff429326bd30bef749e5766174a8f3fece0fe7c0c200c7aa6fa995ff91e4db4de57a76fedb10eec709a7d82ae8ae6140fca85b08653

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
